preprocess_data:
  input: /media/vutrungnghia/New Volume/ArtificialIntelligence/dataset/supervised-learning/raw
  output: /media/vutrungnghia/New Volume/ArtificialIntelligence/dataset/supervised-learning/processed

encode_data:
  input: /media/vutrungnghia/New Volume/ArtificialIntelligence/dataset/supervised-learning/processed
  output: /media/vutrungnghia/New Volume/ArtificialIntelligence/dataset/supervised-learning/encoded
