# dataroot: /content/gdrive/My Drive/MOUNT/encoded-data
dataroot: /media/vutrungnghia/New Volume/ArtificialIntelligence/dataset/supervised-learning/2020-january/encoded-data
train:
  1: 0_500.pkl
  2: 500_1000.pkl
  3: 1000_1500.pkl
  4: 1500_2000.pkl
  5: 2000_2500.pkl
  6: 2500_3000.pkl
  7: 3000_3500.pkl
valid:
  1: 3500_4000.pkl

resume: /content/gdrive/My Drive/MOUNT/models/checkpoint_20-04-22_20:22:34_9.pth
