root: /content/gdrive/My Drive/MOUNT/encoded-data
#root: /media/vutrungnghia/New Volume/ArtificialIntelligence/dataset/supervised-learning/cloud-form
train: [
    2017_black_0_500.pkl,
    2017_black_1000_1500.pkl,
    2017_black_1500_2000.pkl,
    2017_black_500_1000.pkl,
    2017_white_1000_1500.pkl,
    2017_white_1500_2000.pkl,
    2017_white_1_500.pkl,
    2017_white_500_1000.pkl,
    2018_black_0_500.pkl,
    2018_black_500_1000.pkl,
    2018_black_1000_1500.pkl,
    2018_black_1500_2000.pkl,
    2018_white_1_500.pkl,
    2018_white_500_1000.pkl,
    2018_white_1000_1500.pkl,
    2018_white_1500_2000.pkl,
    2019_black_0_500.pkl,
    2019_white_1_500.pkl
]

train_test: [
    2019_black_0_500.pkl,
    2019_white_1_500.pkl
    ]

valid: [
    2020_black_0_500.pkl,
    2020_white_1_500.pkl
]

resume: '' #/content/gdrive/My Drive/MOUNT/models/checkpoint_20-04-26_19:30:25_8.pth
