# root: /content/gdrive/My Drive/MOUNT/encoded-data
root: /media/vutrungnghia/New Volume/ArtificialIntelligence/dataset/supervised-learning/cloud-form
train: [
  2017_black_0_500.pkl,
  2017_white_0_500.pkl,
  2018_black_0_500.pkl,
  2018_white_0_500.pkl,
  2019_black_0_500.pkl,
  2019_white_0_500.pkl
]

valid: [
  2020_black_0_314.pkl,
  2020_white_0_298.pkl
]

resume: ''
