dataroot: /media/vutrungnghia/New Volume/ArtificialIntelligence/Dataset/reinforcement-learning
modelsroot: /media/vutrungnghia/New Volume/ArtificialIntelligence/Models/RL
last_iter:  # get from args

self_play:
  start_game: 0
  end_game: 15
  n_processes: 32
  n_moves: 512
  n_simulation: 400

training:
  epochs: 10
  batch_size: 200
  lr: 0.001
 