dataroot: /media/vutrungnghia/New Volume/ArtificialIntelligence/Dataset/reinforcement-learning
modelsroot: /media/vutrungnghia/New Volume/ArtificialIntelligence/Models/RL
last_iter: 0

self_play:
  start_game: 0
  end_game: 10
  n_processes: 4
  n_moves: 10
  n_simulation: 10

training:
  epochs: 5
  batch_size: 32
  lr: 0.001
